### ISSUE TITLE
Error:   The package node must contain at least one "license" tag

### ISSUE THREAD

**Issue by Desoky01** [jusgomen/ros-mpu9250-imu#2]
Error(s) in package '/home/pi/catkin_ws/src/ros-mpu9250-imu/package.xml':
The package node must contain at least one "license" tag

**Comment by vatsalkshah** [comment]
@Desoky01 were you able to fix the issue? I am getting the same error

**Comment by Desoky01** [comment]
I did not fix it yet

**Comment by robert-meiner** [comment]
Does a fix for this exist?  I am gettin the same error.  I see that people were able to get past this

**Comment by robert-meiner** [comment]
This is fixed in the code [here](https://github.com/jusgomen/ros-mpu9250-imu/pull/4#issue-353289193)

**Comment by Desoky01** [comment]
> This is fixed in the code [here](https://github.com/jusgomen/ros-mpu9250-imu/pull/4#issue-353289193)

Thanks a lot. "fixed"
